# Generated by Django 4.2.7 on 2025-12-31 16:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='trips.trip', verbose_name='trip')),
            ],
            options={
                'verbose_name': 'itinerary',
                'verbose_name_plural': 'itineraries',
                'db_table': 'itineraries',
                'ordering': ['date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('start_time', models.TimeField(blank=True, db_index=True, null=True, verbose_name='start time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='end time')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='location')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='itineraries.itinerary', verbose_name='itinerary')),
            ],
            options={
                'verbose_name': 'itinerary item',
                'verbose_name_plural': 'itinerary items',
                'db_table': 'itinerary_items',
                'ordering': ['order', 'start_time'],
                'indexes': [models.Index(fields=['itinerary', 'order'], name='item_itinerary_order_idx'), models.Index(fields=['itinerary', 'start_time'], name='item_itinerary_time_idx'), models.Index(fields=['itinerary', 'order', 'start_time'], name='item_itinerary_order_time_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='itineraryitem',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gte', models.F('start_time')), ('start_time__isnull', True), ('end_time__isnull', True), _connector='OR'), name='item_valid_time_range'),
        ),
        migrations.AddConstraint(
            model_name='itineraryitem',
            constraint=models.CheckConstraint(check=models.Q(('order__gte', 0)), name='item_positive_order'),
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['trip', 'date'], name='itinerary_trip_date_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['trip', 'date', '-created_at'], name='itinerary_trip_date_crt_idx'),
        ),
        migrations.AddConstraint(
            model_name='itinerary',
            constraint=models.UniqueConstraint(fields=('trip', 'date'), name='unique_trip_date_itinerary'),
        ),
    ]
