# Generated by Django 4.2.7 on 2025-12-31 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(db_index=True, max_length=500, verbose_name='question')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('closes_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='closes at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_polls', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='trips.trip', verbose_name='trip')),
            ],
            options={
                'verbose_name': 'poll',
                'verbose_name_plural': 'polls',
                'db_table': 'polls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200, verbose_name='text')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.poll', verbose_name='poll')),
            ],
            options={
                'verbose_name': 'poll option',
                'verbose_name_plural': 'poll options',
                'db_table': 'poll_options',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.polloption', verbose_name='option')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.poll', verbose_name='poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'vote',
                'verbose_name_plural': 'votes',
                'db_table': 'votes',
                'indexes': [models.Index(fields=['poll', 'user'], name='vote_poll_user_idx'), models.Index(fields=['option'], name='vote_option_idx'), models.Index(fields=['user', '-created_at'], name='vote_user_created_idx'), models.Index(fields=['poll', 'option'], name='vote_poll_option_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('poll', 'option', 'user'), name='unique_poll_option_user_vote'),
        ),
        migrations.AddIndex(
            model_name='polloption',
            index=models.Index(fields=['poll', 'order'], name='option_poll_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='polloption',
            constraint=models.CheckConstraint(check=models.Q(('order__gte', 0)), name='option_positive_order'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['trip', '-created_at'], name='poll_trip_created_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['trip', 'is_active', '-created_at'], name='poll_trip_active_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(condition=models.Q(('closes_at__isnull', False), ('is_active', True)), fields=['closes_at'], name='poll_closes_at_idx'),
        ),
    ]
