# Generated by Django 4.2.7 on 2025-12-31 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('start_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('public', 'Public')], default='private', max_length=20, verbose_name='visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_trips', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'trip',
                'verbose_name_plural': 'trips',
                'db_table': 'trips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], db_index=True, default='viewer', max_length=20, verbose_name='role')),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='joined at')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_collaborators', to=settings.AUTH_USER_MODEL, verbose_name='invited by')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='trips.trip', verbose_name='trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_collaborations', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'collaborator',
                'verbose_name_plural': 'collaborators',
                'db_table': 'collaborators',
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['creator', '-created_at'], name='trips_creator_created_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status', 'start_date'], name='trips_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['updated_at'], name='trips_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(condition=models.Q(('visibility', 'public')), fields=['visibility', 'status', '-created_at'], name='trips_public_listing_idx'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date')), ('start_date__isnull', True), ('end_date__isnull', True), _connector='OR'), name='trips_valid_date_range'),
        ),
        migrations.AddIndex(
            model_name='collaborator',
            index=models.Index(fields=['trip', 'user'], name='collab_trip_user_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborator',
            index=models.Index(fields=['user', '-joined_at'], name='collab_user_joined_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborator',
            index=models.Index(fields=['trip', 'role'], name='collab_trip_role_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborator',
            index=models.Index(fields=['user', 'role', '-joined_at'], name='collab_user_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='collaborator',
            constraint=models.UniqueConstraint(fields=('trip', 'user'), name='unique_trip_user_collaboration'),
        ),
    ]
