"""
Local database implementation using Hive.

Provides offline storage for trips, itineraries, polls, and messages.
"""
import 'package:hive/hive.dart';
import 'package:path_provider/path_provider.dart';

/// Local database manager using Hive
class LocalDatabase {
  static LocalDatabase? _instance;
  static LocalDatabase get instance => _instance ??= LocalDatabase._();
  
  LocalDatabase._();
  
  bool _initialized = false;
  
  // Hive boxes
  Box<TripModel>? _tripsBox;
  Box<ItineraryModel>? _itinerariesBox;
  Box<PollModel>? _pollsBox;
  Box<MessageModel>? _messagesBox;
  Box<SyncMetadata>? _syncMetadataBox;
  
  /// Initialize Hive and open boxes
  Future<void> initialize() async {
    if (_initialized) return;
    
    // Initialize Hive
    final appDocumentDir = await getApplicationDocumentsDirectory();
    Hive.init(appDocumentDir.path);
    
    // Register adapters (generated by hive_generator)
    Hive.registerAdapter(TripModelAdapter());
    Hive.registerAdapter(ItineraryModelAdapter());
    Hive.registerAdapter(PollModelAdapter());
    Hive.registerAdapter(MessageModelAdapter());
    Hive.registerAdapter(SyncMetadataAdapter());
    
    // Open boxes
    _tripsBox = await Hive.openBox<TripModel>('trips');
    _itinerariesBox = await Hive.openBox<ItineraryModel>('itineraries');
    _pollsBox = await Hive.openBox<PollModel>('polls');
    _messagesBox = await Hive.openBox<MessageModel>('messages');
    _syncMetadataBox = await Hive.openBox<SyncMetadata>('sync_metadata');
    
    _initialized = true;
  }
  
  // Getters for boxes
  Box<TripModel> get tripsBox {
    if (!_initialized) throw Exception('Database not initialized');
    return _tripsBox!;
  }
  
  Box<ItineraryModel> get itinerariesBox {
    if (!_initialized) throw Exception('Database not initialized');
    return _itinerariesBox!;
  }
  
  Box<PollModel> get pollsBox {
    if (!_initialized) throw Exception('Database not initialized');
    return _pollsBox!;
  }
  
  Box<MessageModel> get messagesBox {
    if (!_initialized) throw Exception('Database not initialized');
    return _messagesBox!;
  }
  
  Box<SyncMetadata> get syncMetadataBox {
    if (!_initialized) throw Exception('Database not initialized');
    return _syncMetadataBox!;
  }
  
  /// Get last sync timestamp for entity type
  DateTime? getLastSyncTimestamp(String entityType) {
    final metadata = _syncMetadataBox!.get(entityType);
    return metadata?.lastSyncTimestamp;
  }
  
  /// Update last sync timestamp for entity type
  Future<void> updateLastSyncTimestamp(String entityType, DateTime timestamp) async {
    final metadata = SyncMetadata(
      entityType: entityType,
      lastSyncTimestamp: timestamp,
    );
    await _syncMetadataBox!.put(entityType, metadata);
  }
  
  /// Clear all data (for logout)
  Future<void> clearAll() async {
    await _tripsBox!.clear();
    await _itinerariesBox!.clear();
    await _pollsBox!.clear();
    await _messagesBox!.clear();
    await _syncMetadataBox!.clear();
  }
  
  /// Close all boxes
  Future<void> close() async {
    await _tripsBox?.close();
    await _itinerariesBox?.close();
    await _pollsBox?.close();
    await _messagesBox?.close();
    await _syncMetadataBox?.close();
    _initialized = false;
  }
}

/// Sync metadata model
@HiveType(typeId: 100)
class SyncMetadata extends HiveObject {
  @HiveField(0)
  final String entityType;
  
  @HiveField(1)
  final DateTime lastSyncTimestamp;
  
  SyncMetadata({
    required this.entityType,
    required this.lastSyncTimestamp,
  });
}

