# Generated by Django 4.2.7 on 2025-12-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_email_4b85f2_idx',
            old_name='users_email_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_date_jo_0c802f_idx',
            old_name='users_date_joined_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='superuser status'),
        ),
    ]
